### ISSUE TITLE
File not found: account.financial.report.csv

### ISSUE THREAD

**Issue by elicoidal** [cysnake4713/oecn_account_print#1]
Hi,
When updating the module with latest commit I have the following error:
Traceback (most recent call last):
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/module/module.py", line 533, in button_immediate_upgrade
    return self._button_immediate_function(cr, uid, ids, self.button_upgrade, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/module/module.py", line 494, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/tools/convert.py", line 890, in convert_file
    fp = misc.file_open(pathname)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/tools/misc.py", line 199, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/tools/misc.py", line 246, in _fileopen
    raise IOError('File not found: %s' % basename)
IOError: File not found: oecn_account_print/data/account.financial.report.csv

**Comment by cysnake4713** [comment]
@elicoidal I test it again and it works fine, Seems a file is missed to pull to github, I will recommit it and please test it again, sorry

**Comment by cysnake4713** [comment]
Seems I accidently add /data directory to .gitignore file, It has been fixed, please try it again, sorry for the trouble

**Comment by elicoidal** [comment]
@cysnake4713 please check issue#2 (https://github.com/cysnake4713/oecn_account_print/issues/2)
