### ISSUE TITLE
When printing the voucher, traceback

### ISSUE THREAD

**Issue by elicoidal** [cysnake4713/oecn_account_print#2]
Traceback (most recent call last):
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/report/models/report.py", line 191, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/report/models/report.py", line 176, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/addons/report/models/report.py", line 152, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_ui_view.py", line 1026, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 262, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 437, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 423, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 437, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 374, in render_tag_esc
    inner = widget.format(template_attributes['esc'], options, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 993, in format
    return escape(self._format(inner, options, qwebcontext))
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 990, in _format
    return self.pool['ir.qweb'].eval_str(inner, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 214, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 206, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 203, in eval
    return qwebcontext.safe_eval(expr)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/addons/base/ir/ir_qweb.py", line 89, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/home/eric/odoo/CVS/8.0/odoo_ocb/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "'NoneType' object is not callable" while evaluating
'paginate(o.line_id, 5) + 1'

**Comment by cysnake4713** [comment]
@elicoidal I'm not sure what cause it, what is odoo_ocb? Maybe it has defferense from odoo official?

**Comment by elicoidal** [comment]
Odoo OCB: github.com/OCA/OCB
It should not be the reason. Anyway we have ported it to v9 already and we should be able to push it to the OCA very soon :)
I will ping you then.
